# Generated by Django 5.0 on 2024-01-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=255, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='library',
            name='publisher',
            field=models.CharField(max_length=255, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='library',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
